### ISSUE TITLE
Enhancement: Banner and Logo Upload

### ISSUE THREAD

**Issue by mgacrama211176** [Hitoru141/EsportsWebsite#29]
Don't need to click Upload to upload the image to storage.

<img width="887" alt="Screenshot 2023-09-03 at 7 46 12 PM" src="https://github.com/Hitoru141/EsportsWebsite/assets/81429150/ce4a4c72-7b20-4f2d-96d0-1fb549621845">

**Comment by tylerbert31** [comment]
Di sha mo work if e largo nakos onChange na fn marlon, mao ge pa addan nako submit. Any alternatives?

![Image](https://github.com/Hitoru141/EsportsWebsite/assets/101559620/46f5048c-c17a-496e-b49b-b617dfe05f98)

**Comment by mgacrama211176** [comment]
#43
