### ISSUE TITLE
Bug: Upload of image improvements

### ISSUE THREAD

**Issue by mgacrama211176** [Hitoru141/EsportsWebsite#31]
What if I don't want to continue with the adding of team but the banner and logo has already been uploaded?

How it can be resolved: 

- No button for upload of image.
- Use an array for logo and banner preview.
- Image will only be uploaded to storage once the user clicks Add button.

<img width="973" alt="Screenshot 2023-09-03 at 7 51 07 PM" src="https://github.com/Hitoru141/EsportsWebsite/assets/81429150/d1986707-ef2f-4a03-91e9-603d60210284">

**Comment by tylerbert31** [comment]
Will await the downloadURL's first before sha mo axios.post
