### ISSUE TITLE
Map added team at ValorantTeam page

### ISSUE THREAD

**Issue by Hitoru141** [Hitoru141/EsportsWebsite#46]
Retreive added team at ValorantTeam page

![Image](https://user-images.githubusercontent.com/36213437/266193455-bd7d743e-016c-4911-afa4-860ccfcbf453.jpg)

**Comment by tylerbert31** [comment]
CSS to be fixed by Steve

![Image](https://github.com/Hitoru141/EsportsWebsite/assets/101559620/08b53e8d-b12d-47a4-8118-e79961c5ce5d)
