### ISSUE TITLE
Enhancement: Add button upon team creation

### ISSUE THREAD

**Issue by mgacrama211176** [Hitoru141/EsportsWebsite#7]
The button on the team creation can be improved for UI/UX

possible Fixes:

- Increase the size of the button.
- Center button.
- increase size of text

![Screenshot 2023-08-29 at 10 57 10 AM](https://github.com/Hitoru141/EsportsWebsite/assets/81429150/d459810a-0c39-44a3-a8bf-d02b13a3208f)

**Comment by Hitoru141** [comment]
![Image](https://github.com/Hitoru141/EsportsWebsite/assets/36213437/71eca18e-dd27-40fc-8bc0-901cb49a1a41)
