### ISSUE TITLE
Enhancement: Create team header

### ISSUE THREAD

**Issue by mgacrama211176** [Hitoru141/EsportsWebsite#8]
The header can only be halved seen

Possible fixes:

- Increase the size of the header background.

![Screenshot 2023-08-29 at 10 59 58 AM](https://github.com/Hitoru141/EsportsWebsite/assets/81429150/22c1c67e-d67d-405b-bf62-8a18f5b0736d)

**Comment by Hitoru141** [comment]
![Image](https://github.com/Hitoru141/EsportsWebsite/assets/36213437/ee14927a-471c-4cf1-bcbe-a09a0918234b)

Issue only appears after add team modal is opened, 
Resolved  by:
Removing the modal  overlay

**Comment by mgacrama211176** [comment]
Please add the merge request resolving this Issue:
